apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
images:
  - name: moriarty/backend-placeholder
    newName: 123456789.dkr.ecr.us-east-1.amazonaws.com/moriarty
    newTag: backend-latest
patches:
  - path: replica-patch.yaml
