apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ems-backend-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mohamednasser221b-web/ArgoCd.git
    targetRevision: main
    path: overlays/dev          # ← Points to the DEV overlay
  destination:
    server: https://kubernetes.default.svc
    namespace: ems-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true