apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
commonLabels:
  app.kubernetes.io/name: ems-backend
  app.kubernetes.io/part-of: ems  # adding labels to all the resources in this kustomization  